# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   milestone:
#     types: [closed]
env:
  SOME_TRUE_VALUE: 'true'
  SOME_FALSE_VALUE: 'false'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: true value
        if: ${{ env.SOME_TRUE_VALUE }}
        run: echo "hello world"
      - name: false value
        if: ${{ env.SOME_FALSE_VALUE }}
        run: echo "hello world"

        
        
